### ISSUE TITLE
Zfs/Zpool properties nota pplied

### ISSUE THREAD

**Issue by hb0nes** [puppetlabs/puppetlabs-zfs_core#92]
## Describe the Bug
```
profile::base::zfs_management::datasets:
  zpool:
    ensure: present
    setuid: off
    devices: off
  zpool/home:
    ensure: present
    mountpoint: /home
    setuid: off
    devices: off
  zpool/srv:
    ensure: present
    mountpoint: /srv
    setuid: off
    devices: off
```
Using the above hiera config, I do not see setuid or devices being applied to zpool.
Furthermore, once the zfs datasets already exist, the properties are also not being set.
```
12:39:44|production|root@ld4-mon-02:~# zfs get devices zpool/srv
NAME       PROPERTY  VALUE    SOURCE
zpool/srv  devices   on       default
12:42:34|production|root@ld4-mon-02:~# zfs get setuid zpool/home
NAME        PROPERTY  VALUE   SOURCE
zpool/home  setuid    on      default
```
## Expected Behavior
Set properties on a pool and datasets.

## Steps to Reproduce
- Configure pool, try to set properties on it.
- Configure datasets.
  - Create datasets by running Puppet.
  - Edit dataset config to set properties.

## Environment
 - Version mod 'puppetlabs-zfs_core', '1.6.1'
 - Platform Debian 12
